[package]
name = "endianness"
version = "0.1.0"
edition = "2021"
authors = ["micro-rust"]

description = "Cross-crate definition of endianness"

license = "MIT"

publish = true

readme = "README.md"
repository = "https://github.com/micro-rust/endianness"



[features]
exotic = []
