[package]
name = "comedian"
version = "0.1.0"
edition = "2018"
authors = "micro-rust"

description = "Cross-crate definition of endianness"

license = "MIT"

publish = true

readme = "README.md"
repository = "https://github.com/micro-rust/comedian"



[features]
exotic = []
